version: '3'

services:

    app:
        build: .
        image: taskforseapp:dev
        environment:
            - PROXY_URL=${PROXY_URL:-http://proxy/db}

    proxy:
        build: proxy/
        image: taskforseproxy:dev
        environment:
            - APP_URL=${APP_URL:-http://app:3000}
            - OAS_URL=${OAS_URL:-http://oas-ui:8080}
        ports:
            - ${PROD_PORT:-8080}:80
        depends_on:
            - app
            - oas-ui

    oas-ui:
        image: swaggerapi/swagger-ui
        environment:
            - URL=/oas/api/taskforse.json
        volumes:
            - ./oas:/usr/share/nginx/html/api
