version: '3'

services:

    app:
        build: .
        image: docker.pkg.github.com/ondata/taskforse.it/taskforseapp:latest
        environment:
            - PROXY_URL=${PROXY_URL:-http://proxy/db}

    proxy:
        build: proxy/
        image: docker.pkg.github.com/ondata/taskforse.it/taskforseproxy:latest
        environment:
            - APP_URL=${APP_URL:-http://app:3000}
            - OAS_URL=${OAS_URL:-http://oas-ui:8080}
        ports:
            - ${PROD_PORT:-8080}:80
        depends_on:
            - app
            - oas-ui

    oas-ui:
        build: oas/
        image: docker.pkg.github.com/ondata/taskforse.it/taskforseoas:latest
